### PR TITLE
Updates dependencies so that vulnerabilities are no longer present.

### LINKED ISSUE #76: Moderate security vulnerability for versions of Axios 0.8.1 - 1.5.1 (Dependency)
This shows a moderate security vulnerability in the `npm audit` text, since PM2 depends on this package. The fixed version is Axios 1.6.0 and higher. I suggest we migrate towards that one.

### PR DESCRIPTION
**Pull request by OIRNOIR**
This may need additional testing, as I was unable to test it. However, I looked through the code and saw that all of the uses of axios seem to remain unchanged through the updated versions. If your environment is setup to test, please test this code before merging and suggest any changes that may need to be made!

Fixes #76

### CODE REVIEW

**Comment by buffcode** [comment]
@Unitech Would you mind to review / merge this? The latest matching `axios` version (0.21.4) was released Sep 6, 2021.

**Comment by OIRNOIR** [comment]
@Unitech I'm sorry to bother you. Are you alive? It would be great if you could review this PR so that this vulnerability can be fixed.

**Comment by humanscape-chan** [comment]
hi. we installed pm2 package in our koa service.
and our current axios version is 1.6.2. 
I'm not sure it's related with axios version, but pm2's --watch command is not working in our product environment.
except that, pm2 with axios 1.6.0 version is working well.

**Review by guizzo — APPROVED** [review]
LGTM

**Comment by adilatilgan** [comment]
I do not think this PR will build, (browserify) I am struggling with alarm for this one as well, I think this repo is dead, try to figure out my self.

**Comment by OIRNOIR** [comment]
> I do not think this PR will build, (browserify) I am struggling with alarm for this one as well, I think this repo is dead, try to figure out my self.

I fixed it not building, thanks for letting me know. Tests are still broken though.

There's a workaround for anyone who really needs this vulnerability fixed. If you put the following into your project's package.json (depending on your package manager), you should be fine!

NPM:
```json
"overrides": {
	"axios": "^1.6.1"
}
```

PNPM:
```json
"pnpm": {
	"overrides": {
		"axios": "^1.6.1"
	}
}
```

Yarn:
```json
"resolutions": {
	"axios": "^1.6.1"
}
```

@Unitech How do these recent commits look?

**Review by mrhammadasif — APPROVED** [review]
LGTM
How about updating the axios to 1.6.5 ??

**Comment by OIRNOIR** [comment]
> LGTM How about updating the axios to 1.6.5 ??

Done!

**Pull request merged**
